FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3.13-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
