pipeline {
    agent { label 'python-exec' }
    environment {
        RAILWAY_TOKEN = credentials('RAILWAY_TOKEN')
        RAILWAY_SERVICE_ID = credentials('RAILWAY_SERVICE_ID')
    }
    stages {
        stage('Build & test') {
            steps {
                echo 'Installing dependencies...'
                sh '''
                  python3 -m venv .venv
                  . .venv/bin/activate
                  pip install --no-cache-dir pylint pylint-json2html pip-audit
                  pip install --quiet --no-cache-dir -r "$WORKSPACE/ci_cd_pipeline/api/requirements.txt"
                '''

                echo 'Running tests'
                sh 'mkdir -p reports'
                sh '''
                  . .venv/bin/activate
                  pylint --fail-under=5.0 --load-plugins=pylint_json2html --output-format=jsonextended "$WORKSPACE/ci_cd_pipeline/api" > reports/pylint.json || true
                  pylint-json2html -f jsonextended -o reports/pylint.html reports/pylint.json
                  pip-audit -r "$WORKSPACE/ci_cd_pipeline/api/requirements.txt" --format markdown --output reports/pip-audit-report.md
                '''

                env.REPORTS_ARCHIVE = "reports.tar.gz"
                sh 'tar -czvf $REPORTS_ARCHIVE reports'
                archiveArtifacts artifacts: env.REPORTS_ARCHIVE, fingerprint: true,  allowEmptyArchive: true
            }
        }
        stage('Deploy') {
            agent { label 'node-exec' }
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                sh '# railway up --service "$RAILWAY_SERVICE_ID"'
            }

        }
    }
    post {
        always {
            copyArtifacts filter: env.REPORTS_ARCHIVE, fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
        }
    }
}
