pipeline {
    agent any
    environment {
        RAILWAY_TOKEN = credentials('RAILWAY_TOKEN')
        RAILWAY_SERVICE_ID = credentials('RAILWAY_SERVICE_ID')
    }
    stages {
        stage('Build') {
            agent { label 'python-exec' }
            steps {
                echo 'Installing dependencies...'
                sh '''
                  python3 -m venv .venv
                  && source .venv/bin/activate
                  && pip install --no-cache-dir pylint pylint-json2html pip-audit
                  && pip install --quiet --no-cache-dir -r "$WORKSPACE/ci_cd_pipeline/api/requirements.txt"
                '''
            }
        }
        stage('Test Python source code') {
            agent { label 'python-exec' }
            steps {
                echo 'Testing..'

                sh 'mkdir -p reports'
                sh '''
                  source .venv/bin/activate
                  && pylint --load-plugins=pylint_json2html --output-format=jsonextended:reports/pylint.html "$WORKSPACE/ci_cd_pipeline/api"
                  && python3 -m pip-audit -r "$WORKSPACE/ci_cd_pipeline/api/requirements.txt" --format markdown --output reports/pip-audit-report.md
                '''
            }
        }
        stage('Deploy') {
            agent { label 'node-exec' }
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                sh 'railway up --service "$RAILWAY_SERVICE_ID"'
            }

        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'reports/**/*',
                             fingerprint: true,
                             allowEmptyArchive: true
        }
    }
}
