pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Installing dependencies...'
                script {
                  try {
                      sh 'chmod +x ./ci_cd_pipeline/scripts/install_python_env.sh'
                      sh './ci_cd_pipeline/scripts/install_python_env.sh'
                  } catch (err) {
                      echo "Caught: ${err}"
                      currentBuild.result = 'FAILURE'
                      error "Lo script di installazione è fallito: ${err.getMessage()}"
                  }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
